baseurl = "https://mccurdyc.dev"
DefaultContentLanguage = "en"
title = "Colton J. McCurdy"
theme = "beautifulhugo"
metaDataFormat = "yaml"
relativeurls = true
staticDir = "static"
themesDir = "themes"
watch = true
useHLJS = false
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
googleAnalytics = "UA-62612842-1"
[taxonomies]
  post = "posts"
  book = "books"
  book-tag = "book-tags"
  post-title = "post-titles"
  book-author = "book-authors"
  post-tag = "post-tags"
  category = "categories"

[Params]
  homeTitle = "Colton J. McCurdy"
  subtitle = "Software. Coffee. Fountain Pens."
  # logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2006-01-02"
  since="2013"
  commit = false
  rss = false
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[[Params.bigimg]]
 src = "images/detroit-street-art.jpg"

[Author]
  name = "Colton J. McCurdy"
  website = "https://mccurdyc.dev"
  email = "coltonjmccurdy@gmail.com"
  github = "mccurdyc"
  twitter = "mccurdycolton"
  linkedin = "mccurdycolton"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    parent = "Blog"
    name = "Posts"
    url = "post"
    weight = 1

[[menu.main]]
    parent = "Blog"
    name = "Post Tags"
    url = "post-tags"
    weight = 2

[[menu.main]]
    parent = "Blog"
    name = "Post Titles"
    url = "posts"
    weight = 3

[[menu.main]]
    name = "Resume"
    url = "resume/curriculum_vitae_mccurdy.pdf"
    weight = 2

[[menu.main]]
    name = "Bookshelf"
    url = ""
    weight = 3

[[menu.main]]
    parent = "Bookshelf"
    name = "Books"
    url = "book"
    weight = 1

[[menu.main]]
    parent = "Bookshelf"
    name = "Book Tags"
    url = "book-tags"
    weight = 2

[[menu.main]]
    parent = "Bookshelf"
    name = "Book Titles"
    url = "books"
    weight = 3

[[menu.main]]
    parent = "Bookshelf"
    name = "Book Authors"
    url = "book-authors"
    weight = 4

[[menu.main]]
    name = "Projects"
    url = "page/projects/"
    weight = 4

[[menu.main]]
    name = "Talks"
    url = "page/talks/"
    weight = 5

[[menu.main]]
    name = "Papers"
    url = "page/papers/"
    weight = 6

[[menu.main]]
    name = "Site"
    url = "page/site/"
    weight = 7
