baseurl = "https://www.mccurdyc.dev"
title = "©oltoM"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "eighties"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "UA-62612842-1"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreErrors = ["error-remote-getjson"]

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "www"
URL = "gs://www.mccurdyc.dev"

[[deployment.matchers]]
pattern = "^.+\\.(jpg|JPG)$"
cacheControl = "no-store, max-age=0, s-maxage=3600"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Colton J. McCurdy"
  twitter = "mccurdycolton"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # homeSubtitle = "Software. Reading. Running. Traveling. Photography."

  # Metadata mostly used in document's head
  description = "©oltoM"
  keywords = ""
  images = [""]

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  # customCSS = []
  # customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  listedContentTypes = ["posts", "books", "photos"]

  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#1b1c1d"

  # Colors for favicons
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoHomeLink = "/"
    path = "/logo.svg"
    # alt = "Your example logo alt text"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = true
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#ffa500"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "1s"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/mccurdycolton"

  [[params.social]]
    name = "email"
    url  = "mailto:coltonjmccurdy+website@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/mccurdyc"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/mccurdycolton"

[languages]
  [languages.en]
    keywords = ""
    copyright = ""

[menu]
  # [[menu.main]]
  #   identifier = "about"
  #   name       = "\"ABOUT\""
  #   url        = "about/"
  [[menu.main]]
    identifier = "books"
    name       = "\"BOOKS\""
    url        = "books/"
  [[menu.main]]
    identifier = "posts"
    name       = "\"NOTES\""
    url        = "posts/"
  [[menu.main]]
    identifier = "photos"
    name       = "\"PHOTOS\""
    url        = "photos/"
  # [[menu.main]]
  #   identifier = "talks"
  #   name       = "\"TALKS\""
  #   url        = "talks/"
  # [[menu.main]]
  #   identifier = "oss"
  #   name       = "\"SOFTWARE\""
  #   url        = "oss/"
  # [[menu.main]]
  #   identifier = "papers"
  #   name       = "\"PAPERS\""
  #   url        = "papers/"
  [[menu.main]]
    identifier = "resume"
    name       = "\"RESUME\""
    url        = "https://docs.google.com/document/d/1PL18wCHQJ7qTU1ELkKPtRENsa3c01_z4WfptpMwbJsk/edit?usp=sharing"
